export const SET_USER = 'SET_USER';
export const SET_TOP_SONGS = 'SET_TOP_SONGS';
export const SET_TOP_SONGS_ERROR = 'SET_TOP_SONGS_ERROR';
export const SET_LOADING_DATA = 'SET_LOADING_DATA';
export const LOAD_MORE_SONGS = 'LOAD_MORE_SONGS';
export const SET_MORE_SONGS = 'SET_MORE_SONGS';
